/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TaipeiHot.JazzChat.UI;

import TaipeiHot.JazzChat.User;
import java.sql.Array;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 * 
 * @author Paul
 */
public class MainWindow extends javax.swing.JFrame {

	/**
	 * Creates new form FreindList
	 */


	public MainWindow() {
                friendModel.addElement("tesing");
		initComponents();
                
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addFirendButton = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        setPreferredSize(new java.awt.Dimension(500, 538));
        setResizable(false);

        addFirendButton.setText("++++");
        addFirendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFirendButtonMouseClicked(evt);
            }
        });

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(addFirendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addFirendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jList1.setModel(friendModel);
        jScrollPane1.setViewportView(jList1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel2MouseClicked
		System.out.println("hahah");
		// TODO add your handling code here:
	}// GEN-LAST:event_jPanel2MouseClicked

	private void addFirendButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_addFirendButtonMouseClicked
		// TODO add your handling code here:
		addFriendDialog.setVisible(true);
	}// GEN-LAST:event_addFirendButtonMouseClicked

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new MainWindow().setVisible(true);
			}
		});
	}

	/* functions and parameters by paul */
	public Map<Integer, RoomWindow> roomWindowMap = new HashMap<Integer, RoomWindow>();
        public Map<Integer, AcceptFriendDialog> AcceptMap= new HashMap<Integer,AcceptFriendDialog>();
	FreindNameAndStatus f = new FreindNameAndStatus();
	LoginDialog loginDialog = new LoginDialog(this, true);
	RegisterDialog registerDialog = new RegisterDialog(this, true);
	AddFriendDialog addFriendDialog = new AddFriendDialog(this, true);
        AcceptFriendWindow acceptFriendWindow = new AcceptFriendWindow();
        public ArrayList<User> userList =new  ArrayList<User>();
        private ArrayList<String> friendName =new ArrayList<String>();
        DefaultListModel friendModel = new DefaultListModel();
        JList friendLsit=new JList();
        public void loginSuccess() {
		loginDialog.setVisible(false);
		setVisible(true);
                acceptFriendWindow.setVisible(true);
	}
	public void loginFail(String messege) {
		loginDialog.setErrorMessege(messege);
	}
        public void loginShow() {
		try {
			// reg.setVisible(true);
			loginDialog.setVisible(true);
			// this.add(b);
			// System.out.print("done");
			// this.add(f);
			// System.out.print("strat");

			// Point p=f.getLocation();
			// System.out.printf("%d %d\n", p.x,p.y);
			// f.setVisible(true);
		} catch (Exception e) {
			// System.out.print("haha");
		}
	}

	public void registerSuccess() {
		registerDialog.setVisible(false);
		System.out.println("register close");
		loginDialog.setVisible(true);
		System.out.println("login show");
	}
	public void registerFail(String messege) {
		registerDialog.setErrorMessege(messege);
	}
	public void registerShow() {
		registerDialog.setVisible(true);
	}

        public void acceptFriendShow(int userId,String userName,String greeting){
            AcceptFriendDialog acceptFriendDialog=new AcceptFriendDialog(this,true,userId);
            AcceptMap.put(userId, acceptFriendDialog);
            acceptFriendDialog.setVisible(true);
        }
        public void accepFriendSccess(int userId,String message){
            AcceptMap.get(userId).setVisible(false);
        }
        public void accepFriendFail(int userId,String message){

        }
        
        public void addFriendSuccess(String message){
            addFriendDialog.setVisible(false);
        }
        public void addFriendFail(String message){
            addFriendDialog.setErrorMessage(message);
        }

	public RoomWindow getRoomById(int roomId) {
		if (roomWindowMap.get(roomId) == (null)) {
			return newRoom(roomId);
		} else
			return roomWindowMap.get(roomId);
	}

	public RoomWindow newRoom(int roomId, String _roomName,
			ArrayList<String> _userNameList) {
		RoomWindow room = new RoomWindow(roomId, _roomName, _userNameList);
		roomWindowMap.put(roomId, room);
		room.setVisible(true);
		return room;
	}

	public RoomWindow newRoom(int roomId) {
		RoomWindow room = new RoomWindow(roomId);
		roomWindowMap.put(roomId, room);
		room.setVisible(true);
		return room;
	}

	public void closeDialog() {
		try {
			loginDialog.setVisible(false);
		} catch (Exception e) {
		}

	}
        public void friendShow(User user){
            userList.add(user);
            friendModel.addElement(user.getNickname());
            friendName.add(user.getNickname());
            jList1=new JList(friendModel);
            
        }
        public void friendListShow(Map<Integer,User> user){
            
        }
        public void setOnlineById(Integer userId){
            
        }
        public void setOfflineById(Integer userId){
            
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFirendButton;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
