/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TaipeiHot.JazzChat.UI;

import TaipeiHot.JazzChat.Client.Client;
import TaipeiHot.JazzChat.User;
import TaipeiHot.JazzChat.Util;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.Box;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JScrollBar;

/**
 * 
 * @author Paul
 */
public class PublicRoom extends javax.swing.JFrame {

	/**
	 * Creates new form RoomWindow
	 */
        public Box box=Box.createVerticalBox();
        public PublicRoom() {
		initComponents();
                roomId = 0;
                try{
                    chatList.setCellRenderer(new ChatCellRender());
                }catch(MalformedURLException e){
                    Util.errorReport(e.getMessage());
                }
                catch(IOException e){
                    Util.errorReport(e.getMessage());
                }
	}
	public PublicRoom(int _roomId, String _roomName,
			ArrayList<String> _userNameList) {
		initComponents();
		roomId = _roomId;
                try{
                    chatList.setCellRenderer(new ChatCellRender());
                }catch(MalformedURLException e){
                    Util.errorReport(e.getMessage());
                }
                catch(IOException e){
                    Util.errorReport(e.getMessage());
                }
	}

	public PublicRoom(int _roomId)  {
		initComponents();
		roomId = _roomId;
                try{
                    chatList.setCellRenderer(new ChatCellRender());
                }catch(MalformedURLException e){
                    Util.errorReport(e.getMessage());
                }
                catch(IOException e){
                    Util.errorReport(e.getMessage());
                }
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        TrolltButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        typeText = new javax.swing.JTextArea();
        sendTextButton = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        inviteBtn = new javax.swing.JButton();
        uploadFileButton = new javax.swing.JButton();
        callButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        chatList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));

        jLayeredPane1.setBackground(new java.awt.Color(102, 204, 255));

        TrolltButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaipeiHot/JazzChat/UI/trollBtnIcon.jpg"))); // NOI18N
        TrolltButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TrolltButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrolltButtonMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TrolltButtonMouseReleased(evt);
            }
        });
        TrolltButton.setBounds(450, 310, 50, 50);
        jLayeredPane1.add(TrolltButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        typeText.setColumns(20);
        typeText.setRows(2);
        typeText.setBorder(null);
        typeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                typeTextKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(typeText);

        jScrollPane1.setBounds(14, 310, 360, 42);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sendTextButton.setIcon(new javax.swing.ImageIcon("D:\\Paul\\coding\\java\\ChetRoom\\src\\TaipeiHot\\JazzChat\\UI\\sendBtnIcon.jpg")); // NOI18N
        sendTextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sendTextButtonMouseReleased(evt);
            }
        });
        sendTextButton.setBounds(390, 310, 50, 50);
        jLayeredPane1.add(sendTextButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jToolBar1.setRollover(true);

        jButton1.setText(">__<");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", " " }));
        jToolBar1.add(jComboBox1);

        inviteBtn.setText("Add Friend");
        inviteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inviteBtnMouseClicked(evt);
            }
        });
        jToolBar1.add(inviteBtn);

        jToolBar1.setBounds(20, 260, 350, 30);
        jLayeredPane1.add(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        uploadFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaipeiHot/JazzChat/UI/uplode.jpg"))); // NOI18N
        uploadFileButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uploadFileButton.setPreferredSize(new java.awt.Dimension(50, 50));
        uploadFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadFileButtonMouseClicked(evt);
            }
        });
        uploadFileButton.setBounds(450, 250, 50, 50);
        jLayeredPane1.add(uploadFileButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        callButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaipeiHot/JazzChat/UI/Video-Transcription-Service.jpeg"))); // NOI18N
        callButton.setToolTipText("");
        callButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        callButton.setMaximumSize(new java.awt.Dimension(50, 50));
        callButton.setMinimumSize(new java.awt.Dimension(30, 30));
        callButton.setPreferredSize(new java.awt.Dimension(50, 50));
        callButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                callButtonMouseClicked(evt);
            }
        });
        callButton.setBounds(390, 250, 50, 50);
        jLayeredPane1.add(callButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(0, 0));

        chatList.setModel(chatModel
        );
        chatList.setValueIsAdjusting(true);
        chatList.setVisibleRowCount(0);
        jScrollPane3.setViewportView(chatList);

        jScrollPane3.setBounds(10, 10, 490, 230);
        jLayeredPane1.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaipeiHot/JazzChat/UI/FireLion.jpg"))); // NOI18N
        jLabel1.setBounds(-20, 0, 550, 380);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Util.errorReport(jComboBox1.getSelectedItem().toString());
        Client.sendImg(roomId,Integer.parseInt(jComboBox1.getSelectedItem().toString()));
    }//GEN-LAST:event_jButton1MouseClicked

    private void uploadFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadFileButtonMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            String fileName=chooser.getSelectedFile().getPath();
            Client.uploadFile(roomId, fileName);
        }
        
    }//GEN-LAST:event_uploadFileButtonMouseClicked

    private void callButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_callButtonMouseClicked
        // TODO add your handling code here:
        Client.startVideoChat(roomId);
    }//GEN-LAST:event_callButtonMouseClicked

    private void TrolltButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrolltButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TrolltButtonMouseReleased

    private void TrolltButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrolltButtonMouseClicked
        // TODO add your handling code here:
        if(troll)troll=false;
        else troll=true;
               
    }//GEN-LAST:event_TrolltButtonMouseClicked

    private void inviteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inviteBtnMouseClicked
        // TODO add your handling code here:
        invite.setVisible(true);
    }//GEN-LAST:event_inviteBtnMouseClicked

	private void sendTextButtonMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_sendTextButtonMouseReleased
		// TODO add your handling code here:
		send();

	}// GEN-LAST:event_sendTextButtonMouseReleased

	private void typeTextKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_typeTextKeyTyped
		// TODO add your handling code here:
		// int a=evt.getKeyChar();
		// System.out.printf("%c %d\n", a,KeyEvent.VK_ENTER);
		if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
			send();
		}
	}// GEN-LAST:event_typeTextKeyTyped

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PublicRoom.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PublicRoom.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PublicRoom.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PublicRoom.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
                            new PublicRoom(1).setVisible(true);
			}
		});
	}

	/* funcrions and parameters by paul */
	private final int roomId;
	private ArrayList<String> userNameList=new ArrayList<String>();
	private String roomName;
        DefaultListModel chatModel = new DefaultListModel();
        
        
	public void roomNameChange(String _roomName) {
		roomName = _roomName;
	}

	public void roomUserNameListChange(ArrayList<String> _userNameList) {
		userNameList = _userNameList;
	}
        public void addUser(User user){
            userNameList.add(user.getNickname());
        }
	public void showMessage(int userId, String text) {
                ImageIcon tmpIcon=MainWindow.iconMap.get(userId);
                chatModel.addElement(new ChatObject(text + "\n",tmpIcon));
                repaint();
                scrollDown();
        }
        public void scrollDown(){
            
            try {
                Thread.sleep(10);
                for(int i=0;i<10;i++){
                JScrollBar vertical=jScrollPane3.getVerticalScrollBar();
                vertical.setMaximum(chatList.getHeight());
                //vertical.setValue(vertical.getMaximum());
                Util.errorReport(vertical.getMaximum()+" ");
                vertical.setValue(vertical.getMaximum());
                Util.errorReport(vertical.getMaximum()+" ");
                }
                
            } catch (InterruptedException ex) {
                Logger.getLogger(PublicRoom.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            repaint();
        }
        public void showFile(String myPath,String fileName){
            showMessage(Client.user.id,myPath+" "+fileName);
            scrollDown();
        }
        public void confirmDownload(int roomId,String fileName,String filePath){
           Client.startDownload(roomId, fileName, filePath);
        }
	private void send() {
		
                if (!typeText.getText().equals("")) {
			Client.sendMessage(roomId,typeText.getText());
                        showMessage(Client.user.id, typeText.getText());
			//showMessage("haha",typeText.getText());
                        typeText.setText("");
                        
		}
	}
        public  VideoWindow videoWindow=new VideoWindow();
        public InviteFriendWindow invite=new InviteFriendWindow();
        
        
        
        public void showImg(int userId,String url){

            ImageIcon pIcon=MainWindow.iconMap.get(userId);
            Util.errorReport(url);
            ImageIcon tmpIcon;
            tmpIcon = Util.url2Icon(url, 50);
            chatModel.addElement(new ChatObject(pIcon,tmpIcon));
            scrollDown();
        }
        private boolean troll=false;
        public boolean isTrollMode(){
            return troll;
        }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TrolltButton;
    private javax.swing.JButton callButton;
    private javax.swing.JList chatList;
    private javax.swing.JButton inviteBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton sendTextButton;
    private javax.swing.JTextArea typeText;
    private javax.swing.JButton uploadFileButton;
    // End of variables declaration//GEN-END:variables
}
