/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TaipeiHot.JazzChat.UI;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.ArrayList;

import javax.swing.Box;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JScrollBar;

import TaipeiHot.JazzChat.User;
import TaipeiHot.JazzChat.Util;
import TaipeiHot.JazzChat.Client.Client;

/**
 * 
 * @author Paul
 */
public class RoomWindow extends javax.swing.JFrame {

	/**
	 * Creates new form RoomWindow
	 */
	public Box box = Box.createVerticalBox();

	public RoomWindow() {
		initComponents();
		roomId = 0;
		try {
			chatList.setCellRenderer(new ChatCellRender());
		} catch (MalformedURLException e) {
			Util.errorReport(e.getMessage());
		} catch (IOException e) {
			Util.errorReport(e.getMessage());
		}
	}

	public RoomWindow(int _roomId, String _roomName,
			ArrayList<String> _userNameList) {
		initComponents();
		roomId = _roomId;
		try {
			chatList.setCellRenderer(new ChatCellRender());
		} catch (MalformedURLException e) {
			Util.errorReport(e.getMessage());
		} catch (IOException e) {
			Util.errorReport(e.getMessage());
		}
	}

	public RoomWindow(int _roomId) {
		initComponents();
		roomId = _roomId;
		try {
			chatList.setCellRenderer(new ChatCellRender());
		} catch (MalformedURLException e) {
			Util.errorReport(e.getMessage());
		} catch (IOException e) {
			Util.errorReport(e.getMessage());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jScrollPane1 = new javax.swing.JScrollPane();
		typeText = new javax.swing.JTextArea();
		sendTextButton = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		chatList = new javax.swing.JList();
		jToolBar1 = new javax.swing.JToolBar();
		jButton1 = new javax.swing.JButton();
		uploadFileButton = new javax.swing.JButton();
		callButton = new javax.swing.JButton();

		setBackground(new java.awt.Color(102, 153, 255));

		jLayeredPane1.setBackground(new java.awt.Color(102, 204, 255));

		typeText.setBackground(new java.awt.Color(153, 204, 255));
		typeText.setColumns(20);
		typeText.setRows(2);
		typeText.setBorder(new javax.swing.border.SoftBevelBorder(
				javax.swing.border.BevelBorder.RAISED, null, null,
				new java.awt.Color(0, 0, 0), new java.awt.Color(0, 51, 255)));
		typeText.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyTyped(java.awt.event.KeyEvent evt) {
				typeTextKeyTyped(evt);
			}
		});
		jScrollPane1.setViewportView(typeText);

		jScrollPane1.setBounds(10, 290, 334, 48);
		jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		sendTextButton.setText("jButton1");
		sendTextButton.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				sendTextButtonMouseReleased(evt);
			}
		});
		sendTextButton.setBounds(360, 290, 170, 50);
		jLayeredPane1.add(sendTextButton,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		chatList.setModel(chatModel);
		jScrollPane2.setViewportView(chatList);

		jScrollPane2.setBounds(10, 0, 500, 240);
		jLayeredPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jToolBar1.setRollover(true);

		jButton1.setText("jButton1");
		jButton1.setFocusable(false);
		jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton1MouseClicked(evt);
			}
		});
		jToolBar1.add(jButton1);

		jToolBar1.setBounds(10, 250, 330, 30);
		jLayeredPane1.add(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		uploadFileButton.setText("Upload...");
		uploadFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				uploadFileButtonMouseClicked(evt);
			}
		});
		uploadFileButton.setBounds(440, 250, 90, 23);
		jLayeredPane1.add(uploadFileButton,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		callButton.setText("Call!!!!");
		callButton.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				callButtonMouseClicked(evt);
			}
		});
		callButton.setBounds(360, 250, 67, 23);
		jLayeredPane1.add(callButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLayeredPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 550,
								Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGap(18, 18, 18)
						.addComponent(jLayeredPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 344,
								Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton1MouseClicked
		// TODO add your handling code here:
		Client.sendImg(roomId, 1);
	}// GEN-LAST:event_jButton1MouseClicked

	private void uploadFileButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_uploadFileButtonMouseClicked
		// TODO add your handling code here:
		JFileChooser chooser = new JFileChooser();
		int returnVal = chooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			String fileName = chooser.getSelectedFile().getPath();
			Client.uploadFile(roomId, fileName);
		}

	}// GEN-LAST:event_uploadFileButtonMouseClicked

	private void callButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_callButtonMouseClicked
		// TODO add your handling code here:
		videoWindow.setVisible(true);
		Client.startVideoChat(roomId);
	}// GEN-LAST:event_callButtonMouseClicked

	private void sendTextButtonMouseReleased(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_sendTextButtonMouseReleased
		// TODO add your handling code here:
		send();

	}// GEN-LAST:event_sendTextButtonMouseReleased

	private void typeTextKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_typeTextKeyTyped
		// TODO add your handling code here:
		// int a=evt.getKeyChar();
		// System.out.printf("%c %d\n", a,KeyEvent.VK_ENTER);
		if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
			send();
		}
	}// GEN-LAST:event_typeTextKeyTyped

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RoomWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RoomWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RoomWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RoomWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new RoomWindow(1).setVisible(true);
			}
		});
	}

	/* funcrions and parameters by paul */
	private final int roomId;
	private ArrayList<String> userNameList = new ArrayList<String>();
	private String roomName;
	DefaultListModel chatModel = new DefaultListModel();

	public void roomNameChange(String _roomName) {
		roomName = _roomName;
	}

	public void roomUserNameListChange(ArrayList<String> _userNameList) {
		userNameList = _userNameList;
	}

	public void addUser(User user) {
		userNameList.add(user.getNickname());
	}

	public void showMessage(String name, String text) {
		// Util.errorReport("QQQQQ");
		// JLabel jl=new JLabel(name + ":" + text + "\n");
		chatModel.addElement(name + ":" + text + "\n");
		// box.add(jl);
		// jl.setVisible(true);
		JScrollBar vertical = jScrollPane2.getVerticalScrollBar();
		vertical.setValue(vertical.getMaximum());
	}

	public void showFile(String myPath, String fileName) {
		showMessage("me", myPath + " " + fileName);
	}

	public void confirmDownload(int roomId, String fileName, String filePath) {
		Client.startDownload(roomId, fileName, filePath);
	}

	private void send() {

		if (!typeText.getText().equals("")) {
			Client.sendMessage(roomId, typeText.getText());
			showMessage(Client.user.getNickname(), typeText.getText());
			// showMessage("haha",typeText.getText());
			typeText.setText("");

		}
	}

	public VideoWindow videoWindow = new VideoWindow();

	public void showImg(String name, String url) {
		showMessage(name, url);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton callButton;
	private javax.swing.JList chatList;
	private javax.swing.JButton jButton1;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JButton sendTextButton;
	private javax.swing.JTextArea typeText;
	private javax.swing.JButton uploadFileButton;
	// End of variables declaration//GEN-END:variables
}
